"""change user

Revision ID: 066ae6087c86
Revises: b7113c32f3ac
Create Date: 2025-02-03 15:56:13.065558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "066ae6087c86"
down_revision: Union[str, None] = "b7113c32f3ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("amount_purchases", sa.Integer(), nullable=True))
    op.drop_column("users", "count_bonuses")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("count_bonuses", sa.INTEGER(), nullable=True))
    op.drop_column("users", "amount_purchases")
    # ### end Alembic commands ###
